editor/urls.py
from django.conf.urls import url
from editor import views

urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^perfil/editar$', views.editar_perfil, name='editar_perfil'),
    url(r'^perfil/(?P<username>[\w\-.]+)$', views.perfil, name='perfil'),
    url(r'^noticies$', views.totes_noticies, name='totes_noticies'),
    url(r'^noticies/(?P<id>[0-9]+)$', views.veure_noticia, name='veure_noticia'),
    url(r'^noticies/(?P<id>[0-9]+)/editar$', views.editar_noticia, name='editar_noticia'),
    url(r'^noticies/(?P<id>[0-9]+)/esborrar$', views.esborrar_noticia, name='esborrar_noticia'),
    url(r'^noticies/filtrar$', views.filtrar_noticies, name='filtrar_noticies'),
    url(r'^noticies/crear$', views.crear_noticia, name='crear_noticia')
]

radio/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.auth import views as auth_views
from editor import views as edit_views
from django.urls import reverse_lazy

urlpatterns = [
    # Editor
    url(r'^', include('editor.urls')),
    # Admin
    url(r'^admin/', admin.site.urls),
    # Gestio usuaris
    url(r'^register$', edit_views.registration, name='registration'),
    url(r'^usuaris/recuperar_contrasenya$', edit_views.recuperar_contrasenya, name='recuperar_contrasenya'),
    url(r'^usuaris/canvi_contrasenya$', edit_views.canvi_contrasenya, name='canvi_contrasenya'),
    url(r'^usuaris/gestio$', edit_views.gestio_usuaris, name='gestio_usuaris'),
    url(r'^usuaris/gestio/(?P<username>[\w\-.]+)/confirmar$', edit_views.confirmar_usuari, name='confirmar_usuari'),
    url(r'^usuaris/gestio/(?P<username>[\w\-.]+)/denegar$', edit_views.denegar_usuari, name='denegar_usuari'),
    url(r'^usuaris/gestio/(?P<username>[\w\-.]+)/treure_admin$', edit_views.treure_administrador, name='treure_administrador'),
    url(r'^usuaris/gestio/(?P<username>[\w\-.]+)/fer_admin$', edit_views.fer_administrador, name='fer_administrador'),
    url(r'^usuaris/gestio/(?P<username>[\w\-.]+)/esborrar$', edit_views.esborrar_usuari, name='esborrar_usuari'),
    # Errors
    url(r'^not-staff$', edit_views.not_staff, name='not_staff'),
    url(r'^sense_permis$', edit_views.sense_permis, name='sense_permis'),
    # Login
    url(r'^login$', auth_views.login, name='login'),
    url(r'^logout$', auth_views.logout, {'next_page': reverse_lazy('index')}, name='logout'),
] + static(settings.STATIC_URL)

editor/models.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.contrib.auth.models import User
from django.db import models


# Create your models here.
class Perfil(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    telefon = models.CharField(max_length=15, null=True)
    facebook = models.CharField(max_length=100, null=True)
    linkedin = models.CharField(max_length=100, null=True)
    twitter = models.CharField(max_length=100, null=True)


class Noticia(models.Model):
    SECCIONS = (
        ('L', 'Local'),
        ('I', 'Internacional'),
        ('P', 'Política'),
        ('E', 'Economia'),
        ('S', 'Esports'),
        ('O', 'Opinió'),
        ('A', 'Altres'),

    )
    seccio = models.CharField(max_length=1, choices=SECCIONS, default='A')
    titular = models.CharField(max_length=500)
    cos_noticia = models.TextField()
    autor = models.ForeignKey(User, on_delete=models.CASCADE)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

editor/views.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

import os
import random
import string

import sendgrid
from django.contrib.admin.views.decorators import staff_member_required
from django.contrib.auth import authenticate
from django.contrib.auth import login
from django.contrib.auth.decorators import login_required
from django.contrib.auth.models import User
from django.http import HttpResponseRedirect, HttpResponseNotFound, HttpResponseNotAllowed
from django.shortcuts import render
from django.urls import reverse_lazy

from .forms import NoticiaForm, RegistrarUsuariForm, CanviContrasenyaForm, RecuperarContrasenyaForm, PerfilForm
from .models import Noticia, Perfil


def base_context(request):
    context = {
        'n_notificacions': 0,
        'peticions_de_registre': 0,
    }
    if request.user.is_superuser:
        peticions_registre = User.objects.filter(is_staff=False).count()
        if peticions_registre > 0:
            context['n_notificacions'] += peticions_registre
            context['peticions_de_registre'] = peticions_registre
    return context


################################
#            Usuaris           #
################################


def registration(request):
    context = {}
    if request.method == "POST":
        form = RegistrarUsuariForm(request.POST)
        if form.is_valid():
            user = form.save()
            login(request, user)
            return HttpResponseRedirect(reverse_lazy('index'))
    else:
        form = RegistrarUsuariForm()

    context['form'] = form
    return render(request, 'registration/registration.html', context)


def recuperar_contrasenya(request):
    context = {}
    if request.method == "POST":
        form = RecuperarContrasenyaForm(request.POST)
        if form.is_valid():
            email = form.cleaned_data['email']
            if User.objects.filter(email=email).exists():
                random_string = ''.join(
                    random.choice(string.ascii_uppercase + string.ascii_lowercase + string.digits) for _ in range(10))
                user = User.objects.get(email=email)
                user.set_password(random_string)
                user.save()
                sg = sendgrid.SendGridAPIClient(api_key=os.environ.get('SENDGRID_API_KEY'))
                data = {
                    "personalizations": [
                        {
                            "to": [
                                {
                                    "email": email
                                }
                            ],
                            "subject": "Nova contrasenya per Radio-Noticies"
                        }
                    ],
                    "from": {
                        "email": "noreply@radionoticies.com"
                    },
                    "content": [
                        {
                            "type": "text/plain",
                            "value": "La nova contrasenya és: {}".format(random_string)
                        }
                    ]
                }

                sg.client.mail.send.post(request_body=data)
                context['missatge'] = "S'ha enviat un mail amb la nova contrasenya"
            else:
                context['missatge'] = "No hi ha cap usuari amb aquest email"

    else:
        form = RecuperarContrasenyaForm()

    context['form'] = form
    return render(request, 'registration/recuperar_contrasenya.html', context)


@login_required(login_url=reverse_lazy('login'))
def canvi_contrasenya(request):
    context = {}
    if request.method == "POST":
        form = CanviContrasenyaForm(request.POST)
        if form.is_valid():
            username = request.user.username
            password = form.cleaned_data['password_antic']

            user = authenticate(username=username, password=password)
            if user is not None:
                user.set_password(form.cleaned_data['password1'])
                user.save()
                return HttpResponseRedirect(reverse_lazy('index'))
            else:
                context['form'] = form
                context['error'] = 'Contrasenya antiga incorrecta'
                return render(request, 'registration/canvi_contrasenya.html', context)
    else:
        form = CanviContrasenyaForm()

    context['form'] = form
    return render(request, 'registration/canvi_contrasenya.html', context)


@login_required(login_url=reverse_lazy('login'))
def gestio_usuaris(request):
    if request.user.is_superuser:
        context = base_context(request)
        users = User.objects.all()
        context['users'] = users
        return render(request, 'registration/gestio_usuaris.html', context)
    else:
        return HttpResponseRedirect(reverse_lazy('sense_permis'))


@login_required(login_url=reverse_lazy('login'))
def confirmar_usuari(request, username):
    if request.user.is_superuser:
        User.objects.filter(username=username).update(is_staff=True)
        sg = sendgrid.SendGridAPIClient(api_key=os.environ.get('SENDGRID_API_KEY'))
        data = {
            "personalizations": [
                {
                    "to": [
                        {
                            "email": User.objects.get(username=username).email
                        }
                    ],
                    "subject": "Acces a Radio-Noticies"
                }
            ],
            "from": {
                "email": "noreply@radionoticies.com"
            },
            "content": [
                {
                    "type": "text/plain",
                    "value": "L'administrador ja t'ha donat d'alta i pots accedir a la plataforma. Benvingut!"
                }
            ]
        }

        sg.client.mail.send.post(request_body=data)
        context = base_context(request)
        users = User.objects.all()
        context['users'] = users
        return render(request, 'registration/gestio_usuaris.html', context)
    else:
        return HttpResponseRedirect(reverse_lazy('sense_permis'))


@login_required(login_url=reverse_lazy('login'))
def denegar_usuari(request, username):
    if request.user.is_superuser:
        User.objects.filter(username=username).delete()
        context = base_context(request)
        users = User.objects.all()
        context['users'] = users
        return render(request, 'registration/gestio_usuaris.html', context)
    else:
        return HttpResponseRedirect(reverse_lazy('sense_permis'))


@login_required(login_url=reverse_lazy('login'))
def treure_administrador(request, username):
    if request.user.is_superuser:
        User.objects.filter(username=username).update(is_superuser=False)
        context = base_context(request)
        users = User.objects.all()
        context['users'] = users
        return render(request, 'registration/gestio_usuaris.html', context)
    else:
        return HttpResponseRedirect(reverse_lazy('sense_permis'))


@login_required(login_url=reverse_lazy('login'))
def fer_administrador(request, username):
    if request.user.is_superuser:
        User.objects.filter(username=username).update(is_superuser=True)
        context = base_context(request)
        users = User.objects.all()
        context['users'] = users
        return render(request, 'registration/gestio_usuaris.html', context)
    else:
        return HttpResponseRedirect(reverse_lazy('sense_permis'))


@login_required(login_url=reverse_lazy('login'))
def esborrar_usuari(request, username):
    if request.user.is_superuser:
        User.objects.filter(username=username).delete()
        context = base_context(request)
        users = User.objects.all()
        context['users'] = users
        return render(request, 'registration/gestio_usuaris.html', context)
    else:
        return HttpResponseRedirect(reverse_lazy('sense_permis'))


@login_required(login_url=reverse_lazy('login'))
def not_staff(request):
    context = {}
    return render(request, 'error/not_staff.html', context)


@login_required(login_url=reverse_lazy('login'))
def sense_permis(request):
    context = {}
    return render(request, 'error/sense_permis.html', context)


################################
#            Index             #
################################

@login_required(login_url=reverse_lazy('login'))
@staff_member_required(login_url=reverse_lazy('not_staff'))
def index(request):
    context = base_context(request)
    noticies = Noticia.objects.all().order_by('-updated_at')[:10]
    context['noticies'] = noticies
    return render(request, 'index/index.html', context)


@login_required(login_url=reverse_lazy('login'))
@staff_member_required(login_url=reverse_lazy('not_staff'))
def perfil(request, username):
    context = base_context(request)
    user = User.objects.get(username=username)
    noticies = Noticia.objects.filter(autor=user)
    pot_editar = username == request.user.username
    perfil, creat = Perfil.objects.get_or_create(user=request.user)
    context['user'] = user
    context['perfil'] = perfil
    context['noticies'] = noticies
    context['pot_editar'] = pot_editar
    return render(request, 'perfil/index.html', context)


@login_required(login_url=reverse_lazy('login'))
@staff_member_required(login_url=reverse_lazy('not_staff'))
def editar_perfil(request):
    context = base_context(request)
    if request.method == "POST":
        form = PerfilForm(request.POST)
        if form.is_valid():
            nom = form.cleaned_data['nom']
            cognom = form.cleaned_data['cognom']
            email = form.cleaned_data['email']
            telefon = form.cleaned_data['telefon']
            facebook = form.cleaned_data['facebook']
            linkedin = form.cleaned_data['linkedin']
            twitter = form.cleaned_data['twitter']
            User.objects.filter(username=request.user.username).update(email=email, first_name=nom, last_name=cognom)
            perfil = Perfil.objects.get(user=request.user)
            perfil.telefon = telefon

editor/templates/perfil/edit.html
{% extends 'base.html' %}
{% load static %}

{% block head %}
{% endblock %}

{% block content %}

<div class=" col-sm-12" >
    <div class="card">
        <div class="card-header"><strong class="card-title">Editar perfil</strong>

        </div>
        <div class="card-body">
            <form action="{% url 'editar_perfil' %}" method="post">
                {% csrf_token %}
                {{ form.as_p }}
                <input type="submit" value="Guardar" class="btn btn-primary">
            </form>
        </div>
    </div>
</div><!-- /#right-panel -->
{% endblock %}

editor/templates/perfil/index.html
{% extends 'base.html' %}
{% load static %}

{% block head %}

    <link rel="stylesheet" href="{% static "sufee-admin-dashboard-master/vendors/datatables.net-bs4/css/dataTables.bootstrap4.min.css" %}">
    <link rel="stylesheet" href="{% static "sufee-admin-dashboard-master/vendors/datatables.net-buttons-bs4/css/buttons.bootstrap4.min.css" %}">

    <link rel="stylesheet" href="{% static "sufee-admin-dashboard-master/assets/css/style.css" %}">
    <link rel="stylesheet" href="{% static "css/custom.css" %}">
{% endblock %}


{% block content %}
<div class="col-md-12">
    <div class="card">
        <div class="card-header">
            <strong class="card-title">{{ user.first_name }} {{ user.last_name }}
            {% if pot_editar %}
                <a class="btn btn-sm btn-secondary" style="border-radius: 50%;" href="{% url 'editar_perfil' %}"><i class="fa fa-edit"></i></a>
            {% endif %}
            </strong>

        </div>
        <div class="card-body">
            <p style="margin-left: 10px">
                <i class="fa fa-envelope-o user_info"></i>{{ user.email }}
                <br>
                <i class="fa fa-phone user_info"></i>{% if perfil.telefon != None %}{{ perfil.telefon }} {% endif %}
                <br>
                <i class="fa fa-facebook user_info"></i>{% if perfil.facebook != None %}{{ perfil.facebook }} {% endif %}
                <br>
                <i class="fa fa-linkedin user_info"></i>{% if perfil.linkedin != None %}{{ perfil.linkedin }} {% endif %}
                <br>
                <i class="fa fa-twitter user_info"></i>{% if perfil.twitter != None %}{{ perfil.twitter }} {% endif %}
            </p>
        </div>
    </div>
    <div class="card">
        <div class="card-header">
            <strong class="card-title">Noticies escrites</strong>
        </div>
        <div class="card-body">
            <table id="taula-totes-noticies" class="table table-striped table-bordered">
                <thead>
                    <tr>
                        <th>Secció</th>
                        <th>Titular</th>
                        <th>Data</th>
                        {% if user == request.user %}<th>Opcions</th>{% endif %}
                    </tr>
                </thead>
                <tbody>
                {% for noticia in noticies %}
                    <tr>
                        <td style="cursor: pointer" onclick="window.location.href='{% url 'veure_noticia' noticia.id %}'">{{ noticia.get_seccio_display }}</td>
                        <td style="cursor: pointer" onclick="window.location.href='{% url 'veure_noticia' noticia.id %}'">{{ noticia.titular }}</td>
                        <td style="cursor: pointer" onclick="window.location.href='{% url 'veure_noticia' noticia.id %}'">{{ noticia.updated_at|date:"d-n-Y (H:i)" }}</td>
                        {% if user == request.user %}
                        <td>
                            <a class="btn btn-sm btn-secondary" style="border-radius: 24px" href="{% url 'editar_noticia' noticia.id %}"><i class="fa fa-edit "></i></a>
                            <button class="btn btn-sm btn-danger" style="border-radius: 24px" onclick="esborrar('{% url 'esborrar_noticia' noticia.id %}')"><i class="fa fa-close"></i></button>
                        </td>
                        {% endif %}
                    </tr>
                {% endfor %}
                </tbody>
            </table>
        </div>
    </div>
</div>
{% endblock %}


{% block scripts %}
    <script src="{% static "sufee-admin-dashboard-master/vendors/datatables.net/js/jquery.dataTables.min.js" %}"></script>
    <script src="{% static "sufee-admin-dashboard-master/vendors/datatables.net-bs4/js/dataTables.bootstrap4.min.js" %}"></script>
    <script src="{% static "sufee-admin-dashboard-master/vendors/datatables.net-buttons/js/dataTables.buttons.min.js" %}"></script>
    <script src="{% static "sufee-admin-dashboard-master/vendors/datatables.net-buttons-bs4/js/buttons.bootstrap4.min.js" %}"></script>
    <script src="{% static "sufee-admin-dashboard-master/vendors/jszip/dist/jszip.min.js" %}"></script>
    <script src="{% static "sufee-admin-dashboard-master/vendors/pdfmake/build/pdfmake.min.js" %}"></script>
    <script src="{% static "sufee-admin-dashboard-master/vendors/pdfmake/build/vfs_fonts.js" %}"></script>
    <script src="{% static "sufee-admin-dashboard-master/vendors/datatables.net-buttons/js/buttons.html5.min.js" %}"></script>
    <script src="{% static "sufee-admin-dashboard-master/vendors/datatables.net-buttons/js/buttons.print.min.js" %}"></script>
    <script src="{% static "sufee-admin-dashboard-master/vendors/datatables.net-buttons/js/buttons.colVis.min.js" %}"></script>
    <script src="{% static "sufee-admin-dashboard-master/assets/js/init-scripts/data-table/datatables-init.js" %}"></script>

    <script>
    $(document).ready(function() {
        $('#taula-totes-noticies').DataTable( {
            "language": {
                "url":"http://cdn.datatables.net/plug-ins/1.10.19/i18n/Catalan.json"
            }
        } );

    } );
    </script>
    <script>
        function esborrar(url) {
           if (confirm('Estar segur que la vols esborrar?')) {
               location.href = url;
           } else {
               return false;
           }
        }
    </script>
{% endblock %}